import { createHash, randomBytes } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";

interface OAuthBrokerOptions { issuer:string; publicOrigin:string; scopes:string[]; transactionTtlMs?:number; }
interface PendingAuthorization { clientId:string; downstreamRedirectUri:string; downstreamState:string; downstreamCodeChallenge:string; resource:string; upstreamCodeVerifier:string; createdAt:number; }
interface PendingTokenExchange extends PendingAuthorization { upstreamCode:string; }
type JsonObject=Record<string,unknown>;
function base64url(value:Buffer){return value.toString("base64").replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function randomUrlSafe(bytes=32){return base64url(randomBytes(bytes));}
function pkceChallenge(verifier:string){return base64url(createHash("sha256").update(verifier).digest());}
function cors(res:ServerResponse){res.setHeader("access-control-allow-origin","*");res.setHeader("access-control-allow-methods","GET, POST, OPTIONS");res.setHeader("access-control-allow-headers","Authorization, Content-Type");res.setHeader("vary","Origin");}
function json(res:ServerResponse,status:number,body:unknown){cors(res);const data=JSON.stringify(body);res.statusCode=status;res.setHeader("content-type","application/json; charset=utf-8");res.setHeader("cache-control","no-store");res.setHeader("pragma","no-cache");res.setHeader("content-length",Buffer.byteLength(data));res.end(data);}
function redirect(res:ServerResponse,location:string){res.statusCode=302;res.setHeader("location",location);res.setHeader("cache-control","no-store");res.end();}
async function readBody(req:IncomingMessage,maxBytes=1024*1024){const chunks:Buffer[]=[];let total=0;for await(const chunk of req){const value=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=value.length;if(total>maxBytes)throw new Error("REQUEST_BODY_TOO_LARGE");chunks.push(value);}return Buffer.concat(chunks).toString("utf8");}
function requiredParam(params:URLSearchParams,name:string){const value=params.get(name);if(!value)throw new Error(`MISSING_${name.toUpperCase()}`);return value;}

export class OAuthBroker{
 private readonly issuer:string;private readonly publicOrigin:string;private readonly callbackUrl:string;private readonly resourceUri:string;private readonly scopes:string[];private readonly ttlMs:number;private readonly pendingAuthorizations=new Map<string,PendingAuthorization>();private readonly pendingTokens=new Map<string,PendingTokenExchange>();
 constructor(options:OAuthBrokerOptions){this.issuer=options.issuer.replace(/\/$/,"");this.publicOrigin=options.publicOrigin.replace(/\/$/,"");this.callbackUrl=`${this.publicOrigin}/oauth/callback`;this.resourceUri=`${this.publicOrigin}/mcp`;this.scopes=[...new Set(["openid","profile","email","offline_access",...options.scopes])];this.ttlMs=options.transactionTtlMs??10*60*1000;}
 authorizationServerMetadata():JsonObject{return{issuer:this.publicOrigin,authorization_endpoint:`${this.publicOrigin}/oauth/authorize`,token_endpoint:`${this.publicOrigin}/oauth/token`,registration_endpoint:`${this.publicOrigin}/oauth/register`,response_types_supported:["code"],grant_types_supported:["authorization_code","refresh_token"],token_endpoint_auth_methods_supported:["none"],code_challenge_methods_supported:["S256"],scopes_supported:this.scopes,authorization_response_iss_parameter_supported:true};}
 async handle(req:IncomingMessage,res:ServerResponse,requestUrl:URL){this.cleanup();const path=requestUrl.pathname;if(!["/oauth/register","/oauth/authorize","/oauth/callback","/oauth/token"].includes(path))return false;if(req.method==="OPTIONS"){cors(res);res.statusCode=204;res.setHeader("access-control-max-age","86400");res.end();return true;}try{if(path==="/oauth/register")await this.register(req,res);else if(path==="/oauth/authorize")this.authorize(req,res,requestUrl);else if(path==="/oauth/callback")this.callback(req,res,requestUrl);else await this.token(req,res);}catch(error){const message=error instanceof Error?error.message:String(error);json(res,400,{error:"invalid_request",error_description:message});}return true;}
 private cleanup(){const cutoff=Date.now()-this.ttlMs;for(const[k,v]of this.pendingAuthorizations)if(v.createdAt<cutoff)this.pendingAuthorizations.delete(k);for(const[k,v]of this.pendingTokens)if(v.createdAt<cutoff)this.pendingTokens.delete(k);}
 private async register(req:IncomingMessage,res:ServerResponse){if(req.method!=="POST")return json(res,405,{error:"method_not_allowed"});const body=JSON.parse(await readBody(req)) as JsonObject;const redirectUris=Array.isArray(body.redirect_uris)?body.redirect_uris.filter((v):v is string=>typeof v==="string"):[];if(redirectUris.length===0)throw new Error("redirect_uris is required");const upstreamPayload:JsonObject={...body,redirect_uris:[...new Set([...redirectUris,this.callbackUrl])],token_endpoint_auth_method:"none"};const response=await fetch(`${this.issuer}/oauth/register`,{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify(upstreamPayload)});const text=await response.text();cors(res);res.statusCode=response.status;res.setHeader("content-type",response.headers.get("content-type")??"application/json; charset=utf-8");res.setHeader("cache-control","no-store");res.end(text);}
 private authorize(req:IncomingMessage,res:ServerResponse,requestUrl:URL){if(req.method!=="GET")return json(res,405,{error:"method_not_allowed"});const p=requestUrl.searchParams;const responseType=requiredParam(p,"response_type"),clientId=requiredParam(p,"client_id"),downstreamRedirectUri=requiredParam(p,"redirect_uri"),downstreamState=requiredParam(p,"state"),downstreamCodeChallenge=requiredParam(p,"code_challenge"),method=requiredParam(p,"code_challenge_method"),resource=requiredParam(p,"resource");if(responseType!=="code")throw new Error("ONLY_AUTHORIZATION_CODE_SUPPORTED");if(method!=="S256")throw new Error("PKCE_S256_REQUIRED");if(resource!==this.resourceUri)throw new Error("RESOURCE_MISMATCH");const upstreamState=randomUrlSafe(32),upstreamCodeVerifier=randomUrlSafe(64),upstreamChallenge=pkceChallenge(upstreamCodeVerifier);this.pendingAuthorizations.set(upstreamState,{clientId,downstreamRedirectUri,downstreamState,downstreamCodeChallenge,resource,upstreamCodeVerifier,createdAt:Date.now()});const upstream=new URL(`${this.issuer}/oauth/authorize`);for(const[key,value]of p)upstream.searchParams.append(key,value);upstream.searchParams.set("redirect_uri",this.callbackUrl);upstream.searchParams.set("state",upstreamState);upstream.searchParams.set("code_challenge",upstreamChallenge);upstream.searchParams.set("code_challenge_method","S256");upstream.searchParams.set("resource",resource);redirect(res,upstream.toString());}
 private callback(req:IncomingMessage,res:ServerResponse,requestUrl:URL){if(req.method!=="GET")return json(res,405,{error:"method_not_allowed"});const upstreamState=requiredParam(requestUrl.searchParams,"state"),transaction=this.pendingAuthorizations.get(upstreamState);if(!transaction)throw new Error("OAUTH_TRANSACTION_NOT_FOUND_OR_EXPIRED");this.pendingAuthorizations.delete(upstreamState);const downstream=new URL(transaction.downstreamRedirectUri),upstreamError=requestUrl.searchParams.get("error");if(upstreamError){downstream.searchParams.set("error",upstreamError);const description=requestUrl.searchParams.get("error_description");if(description)downstream.searchParams.set("error_description",description);downstream.searchParams.set("state",transaction.downstreamState);downstream.searchParams.set("iss",this.publicOrigin);return redirect(res,downstream.toString());}const upstreamCode=requiredParam(requestUrl.searchParams,"code"),downstreamCode=randomUrlSafe(32);this.pendingTokens.set(downstreamCode,{...transaction,upstreamCode});downstream.searchParams.set("code",downstreamCode);downstream.searchParams.set("state",transaction.downstreamState);downstream.searchParams.set("iss",this.publicOrigin);redirect(res,downstream.toString());}
 private async token(req:IncomingMessage,res:ServerResponse){if(req.method!=="POST")return json(res,405,{error:"method_not_allowed"});const p=new URLSearchParams(await readBody(req)),grantType=requiredParam(p,"grant_type");if(grantType==="authorization_code"){const downstreamCode=requiredParam(p,"code"),transaction=this.pendingTokens.get(downstreamCode);if(!transaction)throw new Error("AUTHORIZATION_CODE_NOT_FOUND_OR_EXPIRED");const clientId=requiredParam(p,"client_id"),redirectUri=requiredParam(p,"redirect_uri"),verifier=requiredParam(p,"code_verifier"),resource=requiredParam(p,"resource");if(clientId!==transaction.clientId)throw new Error("CLIENT_ID_MISMATCH");if(redirectUri!==transaction.downstreamRedirectUri)throw new Error("REDIRECT_URI_MISMATCH");if(resource!==transaction.resource||resource!==this.resourceUri)throw new Error("RESOURCE_MISMATCH");if(pkceChallenge(verifier)!==transaction.downstreamCodeChallenge)throw new Error("PKCE_VERIFIER_MISMATCH");this.pendingTokens.delete(downstreamCode);const upstream=new URLSearchParams({grant_type:"authorization_code",client_id:transaction.clientId,code:transaction.upstreamCode,redirect_uri:this.callbackUrl,code_verifier:transaction.upstreamCodeVerifier,resource:transaction.resource});return this.forwardTokenRequest(res,upstream);}if(grantType==="refresh_token"){const upstream=new URLSearchParams(p);if(!upstream.get("resource"))upstream.set("resource",this.resourceUri);return this.forwardTokenRequest(res,upstream);}json(res,400,{error:"unsupported_grant_type"});}
 private async forwardTokenRequest(res:ServerResponse,params:URLSearchParams){const response=await fetch(`${this.issuer}/oauth/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body:params});const text=await response.text();cors(res);res.statusCode=response.status;res.setHeader("content-type",response.headers.get("content-type")??"application/json; charset=utf-8");res.setHeader("cache-control","no-store");res.setHeader("pragma","no-cache");res.end(text);}
}
