import type { ActorContext, ArtifactKind } from "../../../packages/repositories/src/index.js";
import type { MutationContext, ProjectWorkflowService } from "../../../packages/services/src/index.js";

export interface ToolDefinition {
  name: string;
  title?: string;
  description: string;
  inputSchema: Record<string, unknown>;
  annotations?: { readOnlyHint?: boolean; destructiveHint?: boolean; idempotentHint?: boolean; openWorldHint?: boolean };
  _meta?: Record<string, unknown>;
  execute(input: Record<string, unknown>): Promise<unknown>;
}
export type ActorProvider = () => Promise<ActorContext> | ActorContext;
export type ApprovalGrantExecutor = <T>(input:{token:string;actor:ActorContext;projectId:string;kind:ArtifactKind;artifactVersionId:string}, action:()=>Promise<T>) => Promise<T>;
const ARTIFACT_KINDS: readonly ArtifactKind[] = ["ANALYSIS","STRUCTURE","RESOURCES","ART_DIRECTION","VERIFICATION","DESIGN"];
function strictObject(required:string[],properties:Record<string,unknown>):Record<string,unknown>{return{type:"object",required,additionalProperties:false,properties};}
function reqString(i:Record<string,unknown>,k:string){const v=i[k];if(typeof v!=="string"||v.trim()==="")throw new Error(`INVALID_${k.toUpperCase()}`);return v;}
function reqBoolean(i:Record<string,unknown>,k:string){const v=i[k];if(typeof v!=="boolean")throw new Error(`INVALID_${k.toUpperCase()}`);return v;}
function reqScore(i:Record<string,unknown>,k:string){const v=i[k];if(typeof v!=="number"||!Number.isFinite(v)||v<0||v>100)throw new Error(`INVALID_${k.toUpperCase()}`);return v;}
function reqStringArray(i:Record<string,unknown>,k:string){const v=i[k];if(!Array.isArray(v)||!v.every(x=>typeof x==="string"))throw new Error(`INVALID_${k.toUpperCase()}`);return v as string[];}
async function context(i:Record<string,unknown>,p:ActorProvider):Promise<MutationContext>{return{actor:await p(),requestId:reqString(i,"requestId")};}

export function createVisual4DToolRegistry(workflow:ProjectWorkflowService,actorProvider:ActorProvider,approvalGrantExecutor?:ApprovalGrantExecutor):ToolDefinition[]{
 return [
  {name:"method.analyze",description:"Create an analysis version. Authenticated actor is injected by the server.",inputSchema:strictObject(["projectId","sourceContent","requestId"],{projectId:{type:"string",minLength:1},sourceContent:{type:"string",minLength:1},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.startAnalysis(reqString(i,"projectId"),reqString(i,"sourceContent"),await context(i,actorProvider))},
  {name:"approvals.approve_stage",description:"Consume a one-time user-action approval grant and approve the exact current artifact version.",inputSchema:strictObject(["projectId","kind","artifactVersionId","approvalGrant","requestId"],{projectId:{type:"string",minLength:1},kind:{type:"string",enum:ARTIFACT_KINDS},artifactVersionId:{type:"string",minLength:1},approvalGrant:{type:"string",minLength:16},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>{const kind=reqString(i,"kind") as ArtifactKind;if(!ARTIFACT_KINDS.includes(kind))throw new Error("INVALID_KIND");const actor=await actorProvider();if(!approvalGrantExecutor)throw new Error("APPROVAL_GRANT_EXECUTOR_REQUIRED");const projectId=reqString(i,"projectId"),artifactVersionId=reqString(i,"artifactVersionId");return approvalGrantExecutor({token:reqString(i,"approvalGrant"),actor,projectId,kind,artifactVersionId},()=>workflow.approve(projectId,kind,artifactVersionId,{actor,requestId:reqString(i,"requestId")}));}},
  {name:"method.structure",description:"Create the editorial structure after exact analysis approval.",inputSchema:strictObject(["projectId","payload","requestId"],{projectId:{type:"string",minLength:1},payload:{},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.structure(reqString(i,"projectId"),i.payload,await context(i,actorProvider))},
  {name:"method.resolve_resources",description:"Resolve project-specific resource requirements.",inputSchema:strictObject(["projectId","requestId"],{projectId:{type:"string",minLength:1},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.resolveResources(reqString(i,"projectId"),await context(i,actorProvider))},
  {name:"method.art_direct",description:"Create art direction only when required resources are resolved.",inputSchema:strictObject(["projectId","payload","requestId"],{projectId:{type:"string",minLength:1},payload:{},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.artDirect(reqString(i,"projectId"),i.payload,await context(i,actorProvider))},
  {name:"generation.create_design",description:"Create the DesignVersion that will be verified.",inputSchema:strictObject(["projectId","renderUri","requestId"],{projectId:{type:"string",minLength:1},renderUri:{type:"string",minLength:1},layoutSpecId:{type:"string"},checksumSha256:{type:"string",pattern:"^[a-fA-F0-9]{64}$"},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.createDesignVersion(reqString(i,"projectId"),{renderUri:reqString(i,"renderUri"),...(typeof i.layoutSpecId==="string"?{layoutSpecId:i.layoutSpecId}:{}),...(typeof i.checksumSha256==="string"?{checksumSha256:i.checksumSha256}:{})},await context(i,actorProvider))},
  {name:"verification.save",description:"Verify one exact current DesignVersion.",inputSchema:strictObject(["projectId","designVersionId","passed","criticalErrors","score","requestId"],{projectId:{type:"string",minLength:1},designVersionId:{type:"string",minLength:1},passed:{type:"boolean"},criticalErrors:{type:"array",items:{type:"string"}},score:{type:"number",minimum:0,maximum:100},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.saveVerification(reqString(i,"projectId"),{designVersionId:reqString(i,"designVersionId"),passed:reqBoolean(i,"passed"),criticalErrors:reqStringArray(i,"criticalErrors"),score:reqScore(i,"score")},await context(i,actorProvider))},
  {name:"versions.mark_final",description:"Finalize only after the exact verification version was explicitly user-approved through approvals.approve_stage.",inputSchema:strictObject(["projectId","verificationVersionId","requestId"],{projectId:{type:"string",minLength:1},verificationVersionId:{type:"string",minLength:1},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.approveDesign(reqString(i,"projectId"),reqString(i,"verificationVersionId"),await context(i,actorProvider))},
  {name:"identity.activate_version",description:"Atomically activate an identity version for the authenticated owner.",inputSchema:strictObject(["institutionId","identityVersionId","requestId"],{institutionId:{type:"string",minLength:1},identityVersionId:{type:"string",minLength:1},requestId:{type:"string",minLength:1}}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},execute:async i=>workflow.activateIdentity(reqString(i,"institutionId"),reqString(i,"identityVersionId"),await context(i,actorProvider))}
 ];
}
