import test from "node:test";
import assert from "node:assert/strict";
import { assertPkceS256, defaultOidcDiscoveryUrl, discoverOidcConfiguration, OidcConfigurationError } from "../services/mcp-server/src/oidc-discovery.js";

test("builds RFC 8414 authorization server metadata URL",()=>assert.equal(defaultOidcDiscoveryUrl("https://issuer.example/"),"https://issuer.example/.well-known/oauth-authorization-server"));
test("discovers matching issuer, DCR endpoint, jwks uri and PKCE S256",async()=>{const doc=await discoverOidcConfiguration({issuer:"https://issuer.example",fetchJson:async()=>({issuer:"https://issuer.example",jwks_uri:"https://issuer.example/jwks",registration_endpoint:"https://issuer.example/oauth/register",code_challenge_methods_supported:["S256"]})});assert.equal(doc.jwks_uri,"https://issuer.example/jwks");assert.equal(doc.registration_endpoint,"https://issuer.example/oauth/register");assertPkceS256(doc);});
test("issuer mismatch fails closed",async()=>{await assert.rejects(()=>discoverOidcConfiguration({issuer:"https://issuer.example",fetchJson:async()=>({issuer:"https://evil.example",jwks_uri:"https://evil.example/jwks",code_challenge_methods_supported:["S256"]})}),(e:unknown)=>e instanceof OidcConfigurationError&&e.code==="OIDC_ISSUER_MISMATCH");});
test("provider metadata must advertise PKCE S256",()=>assert.throws(()=>assertPkceS256({issuer:"https://issuer.example",jwks_uri:"https://issuer.example/jwks"}),(e:unknown)=>e instanceof OidcConfigurationError&&e.code==="OIDC_PKCE_S256_REQUIRED"));
test("provider declaring non-S256 PKCE methods fails closed",()=>assert.throws(()=>assertPkceS256({issuer:"https://issuer.example",jwks_uri:"https://issuer.example/jwks",code_challenge_methods_supported:["plain"]}),(e:unknown)=>e instanceof OidcConfigurationError&&e.code==="OIDC_PKCE_S256_REQUIRED"));
